// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;




/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzdcfeaxGdTL2Jg_pncNQQ7bcCoHbaosU',
    appId: '1:612443882098:android:35e8842bd8a898ce33f8eb',
    messagingSenderId: '612443882098',
    projectId: 'tripify-d8b05',
    databaseURL: 'https://tripify-d8b05-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tripify-d8b05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp1O0mMZ73GOcCjp95H-mBywhgKDq3WC0',
    appId: '1:612443882098:ios:9b77fbb8f876b06433f8eb',
    messagingSenderId: '612443882098',
    projectId: 'tripify-d8b05',
    databaseURL: 'https://tripify-d8b05-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tripify-d8b05.appspot.com',
    androidClientId: '612443882098-t6br8nkbieia34mvligltli444aq4u2h.apps.googleusercontent.com',
    iosClientId: '612443882098-5knkh7soqlin4jfpf9qhut6ro534of9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.project2Flutter',
  );
}
